name: "Backup Notion Workspace"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "50 12 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run backup script
        run: npm install && npm run backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
          NOTION_FILKE_TOKEN: ${{ secrets.NOTION_FILE_TOKEN }}
          
      - name: Checkout backup repo
        uses: actions/checkout@v4
        
        with:
          repository: ${{ secrets.REPO_USERNAME }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
          path: "backup-repo"
          ref: main 
      - name: Commit changes to backup repo
        env:
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        run: |
          cp -a workspace/. backup-repo/
          cd backup-repo
          git config --local user.email "${REPO_EMAIL}"
          git config --local user.name "${REPO_USERNAME}"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Automated Notion workspace backup"
          git push
